"""Flask app factory.

BOOTSTRAP ONLY (planv0.2.md section 1). Written once at SYNC-1, then
effectively frozen. B5 and B6 add views to their own blueprint modules; they
do not edit this file. The frontend adds nothing here either.

The one clever thing in here is `_register_contract_stubs`. Every route in
contracts/routes.py gets a URL rule the moment the app starts, whether or not
anyone has implemented it. That means `url_for` works from hour one, so the
frontend can build navigation against routes the backend has not written yet
-- and an unimplemented route answers 501 with a plain message instead of
raising BuildError inside a template.
"""

from __future__ import annotations

import os

from flask import Flask

from contracts.routes import ROUTES

BLUEPRINT_MODULES = {
    "pages": "app.routes.pages",
    "sessions": "app.routes.session",
    "shell": "app.routes.shell",
    # Frontend-owned (planv0.2.md F6). Absent on the backend branch until SYNC-2.
    "preview": "app.preview",
}


def create_app(config: dict | None = None) -> Flask:
    app = Flask(
        __name__,
        template_folder="../templates",
        static_folder="../static",
    )
    app.config.update(
        SECRET_KEY=os.environ.get("RELAY_SECRET_KEY", "dev-only-not-a-secret"),
        DATABASE=os.environ.get("RELAY_DB", "relay.db"),
        AI_PROVIDER=os.environ.get("RELAY_AI_PROVIDER", "ollama"),
        AI_MODEL=os.environ.get("RELAY_MODEL", "gemma4:31b-cloud"),
    )
    if config:
        app.config.update(config)

    _register_blueprints(app)
    _register_contract_stubs(app)
    return app


def _register_blueprints(app: Flask) -> None:
    from importlib import import_module

    for name, module_path in BLUEPRINT_MODULES.items():
        try:
            module = import_module(module_path)
        except ModuleNotFoundError:
            # The other track has not landed this module yet. Its routes still
            # get stub rules below, so url_for keeps working.
            app.logger.info("blueprint '%s' not present yet (%s)", name, module_path)
            continue
        app.register_blueprint(module.bp)


def _register_contract_stubs(app: Flask) -> None:
    """Fill in any contracted route that nobody has implemented yet."""

    def make_stub(key: str):
        def stub(**_kwargs):
            return (
                f"Not implemented yet: {key}. "
                f"This route is declared in contracts/routes.py and will be "
                f"filled in by its owning package.",
                501,
            )

        return stub

    for key, route in ROUTES.items():
        if route.endpoint in app.view_functions:
            continue
        app.add_url_rule(
            route.rule,
            endpoint=route.endpoint,
            view_func=make_stub(key),
            methods=list(route.methods),
        )
